### ISSUE TITLE
Code to generate the localization_cues.pickle

### ISSUE THREAD

**Issue by ppengtang** [kolesman/SEC#12]
Hi,

Could you please provide the complete code to generate the localization_cues.pickle?

I have tried to use the codes under the weak-localization folder to generate the localization_cues.pickle but can only obtain 49.8% on the PASCAL VOC 2012 val set.

Thank you!

**Comment by horserma** [comment]
@ppengtang 
Here is another implementation that includes everything. Check it out
https://github.com/ascust/SEC-MXNet

**Comment by ppengtang** [comment]
@horserma Thanks!

**Comment by XZNWU** [comment]
Could you provide the code to generate the localization_cues.pickle? @ppengtang

**Comment by ppengtang** [comment]
Sorry I cannot find my codes to generate the localization_cues.pickle. Maybe you can check the codes here [https://github.com/ascust/SEC-MXNet](url).

**Comment by XZNWU** [comment]
Thanks @ppengtang
